# Generated by Django 4.0.6 on 2023-04-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_User',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('National_ID', models.CharField(max_length=20)),
                ('Account_Type', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('EVSecurity', 'EVSecurity')], default='User', max_length=10)),
                ('Age', models.PositiveIntegerField()),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Deletion_Date', models.DateTimeField(blank=True, null=True)),
                ('Account_Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tb_Report',
            fields=[
                ('ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Note', models.TextField()),
                ('Type', models.CharField(max_length=255)),
                ('Report_Status', models.CharField(choices=[('Not Confirmed', 'Not Confirmed'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Not Confirmed', max_length=15)),
                ('Added_Date', models.DateTimeField(auto_now_add=True)),
                ('Cancellation_Date', models.DateTimeField(blank=True, null=True)),
                ('IsCancellation', models.BooleanField(default=False)),
                ('Deleted_Date', models.DateTimeField(blank=True, null=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tb_user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Text', models.CharField(max_length=500)),
                ('Attachment', models.ImageField(null=True, upload_to='')),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='user.tb_user')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='user.tb_user')),
            ],
        ),
    ]
