# Generated by Django 4.0.6 on 2023-04-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_report',
            name='Verification_Status',
            field=models.CharField(choices=[('Not Confirmed', 'Not Confirmed'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Not Confirmed', max_length=15),
        ),
        migrations.AlterField(
            model_name='tb_report',
            name='Report_Status',
            field=models.CharField(choices=[('Dealt With', 'Dealt With'), ('Not Dealt With', 'Not Dealt With')], default='Not Dealt With', max_length=30),
        ),
    ]
