# Generated by Django 4.2 on 2023-04-25 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tb_report_verification_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_report',
            name='Location',
        ),
        migrations.AddField(
            model_name='tb_report',
            name='alt',
            field=models.FloatField(default=14.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Reports/'),
        ),
        migrations.AddField(
            model_name='tb_report',
            name='lag',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_report',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_report',
            name='Type',
            field=models.CharField(choices=[('Non-Predator', 'Non-Predator'), ('Predator', 'Predator')], default='Predator', max_length=15),
        ),
    ]
