# Generated by Django 4.2 on 2023-04-25 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_tb_report_location_tb_report_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_user',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
