# Generated by Django 4.2 on 2023-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_tb_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='Nationality',
            field=models.CharField(default='Saudi', max_length=255),
        ),
    ]
