# Generated by Django 4.2 on 2023-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tb_user_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_user',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
