# Generated by Django 4.2 on 2023-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tb_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='Account_Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deleted', 'Deleted')], default='Inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='National_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
