# Generated by Django 4.2.1 on 2023-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_message_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='alt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='lag',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tb_user',
            name='Phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
