# Generated by Django 4.2 on 2023-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_message_alt_message_lag_alter_tb_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='lag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
