# Generated by Django 4.2 on 2023-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_message_alt_alter_message_lag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='alt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='lag',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
