# Generated by Django 4.2 on 2023-06-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_message_alt_alter_message_lag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='IsRead',
            field=models.BooleanField(default=False),
        ),
    ]
