# Generated by Django 4.2 on 2023-06-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_message_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_report',
            name='EVAdmin_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reports', to='user.tb_user'),
        ),
    ]
